project:
  type: website

website:
  title: "CLUB STEM MAIRENA"
  back-to-top-navigation: true
  reader-mode: true
  favicon: /images/logo_juanDeMairena.png
  navbar:
    logo: /images/logo_juanDeMairena.png
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Información
      - href: blog_curso_actual/blog_curso_actual.qmd
        text: Actividades curso actual
      - href: blog_histórico/blog_histórico.qmd
        text: Actividades otros cursos

format:
  html:
    theme: sketchy
    fontcolor: "#24338E"
    css: styles.css
    toc: true

editor: visual
email-obfuscation: javascript


