project:
  type: website

website:
  title: "CLUB STEM MAIRENA"
  navbar:
    left:
#      - href: index.qmd
#        text: Inicio
      - href: about.qmd
        text: Acerca

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

